# Generated by Django 6.1 on 2026-09-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_guests', models.PositiveIntegerField(default=2, help_text='Maximum allowed guest occupancy')),
                ('bed_type', models.CharField(choices=[('KING', '1 King Bed'), ('QUEEN', '1 Queen Bed'), ('TWIN', '2 Twin Beds'), ('DOUBLE', '2 Double Beds'), ('SUITE_MASTER', 'Master King + Sofa Bed')], default='KING', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Standard nightly rate in USD/local currency', max_digits=10)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities (e.g. WiFi, Smart TV, Balcony, Minibar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'db_table': 'room_types',
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Unique room number or suite code', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('DIRTY', 'Dirty (Needs Housekeeping)'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(help_text='Category and pricing rules for this room', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
    ]
