# Generated by Django 6.1 on 2026-09-02 13:46

import apps.bookings.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, default=apps.bookings.models.generate_booking_reference, max_length=50, unique=True)),
                ('check_in_date', models.DateField(db_index=True)),
                ('check_out_date', models.DateField(db_index=True)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('booking_source', models.CharField(choices=[('DIRECT', 'Direct / Website'), ('WALK_IN', 'Front Desk Walk-In'), ('BOOKING_COM', 'Booking.com'), ('EXPEDIA', 'Expedia'), ('AIRBNB', 'Airbnb'), ('CORPORATE', 'Corporate Partner')], default='DIRECT', max_length=50)),
                ('booking_status', models.CharField(choices=[('HOLD', 'On Hold (Awaiting Payment)'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='HOLD', max_length=50)),
                ('hold_expires_at', models.DateTimeField(blank=True, help_text='Auto-cancellation deadline for unpaid hold reservations', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who processed the reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(help_text='Guest holding the reservation', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guests.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_reference'], name='bookings_booking_4d53ac_idx'), models.Index(fields=['check_in_date', 'check_out_date'], name='bookings_check_i_73f05f_idx'), models.Index(fields=['booking_status'], name='bookings_booking_ab1f8c_idx')],
            },
        ),
    ]
