# Generated by Django 6.1 on 2026-09-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(db_index=True, help_text='Primary phone with country code', max_length=30)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Optional guest email for invoice and confirmations', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'db_table': 'guests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='guests_phone_eb3a1e_idx'), models.Index(fields=['email'], name='guests_email_a33f61_idx')],
            },
        ),
    ]
