# Generated by Django 6.1 on 2026-09-02 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WALK_IN', 'Walk-In'), ('OTA', 'OTA / Partner')], default='WEBSITE', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('QUOTED', 'Quoted'), ('CONVERTED', 'Converted to Booking'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff user assigned to follow up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, help_text='Optional link to recognized guest profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='guests.guest')),
                ('preferred_room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
