# Generated by Django 6.1 on 2026-09-02 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monetary amount in standard currency', max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, help_text='Payment gateway transaction ID or receipt #', max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], default='CREDIT_CARD', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(help_text='Booking reservation for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Staff user who verified or accepted this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['transaction_reference'], name='payments_transac_4c44f7_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
    ]
