# Generated by Django 6.1 on 2026-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_pending_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_checkout_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('CHAPA', 'Chapa')], default='CREDIT_CARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID or receipt #', max_length=100, null=True, unique=True),
        ),
    ]
